name: Application One
run-name: SDLC for Application One 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."
  sast:
    needs: build
    uses: devopslord/shared-workflows/.github/workflows/sast.yaml@main
    with:
      run-name: "Static Application Security Testing for Application-One" 
  provision-infra:
    runs-on: ubuntu-latest
    steps:
      - run: echo "⚙️ Provisioning testing infrastructure for Application One."
  dockerise:
    needs: build
    uses: devopslord/application-one/.github/workflows/dockerise.yaml@main
    with:
      image: "application-one"
  end-2-end:
    runs-on: ubuntu-latest
    needs:
      - dockerise
      - provision-infra
    steps:
      - run: echo "⚙️ Running E2E tests"
  promote:
    needs: 
      - end-2-end
      - sast
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/promote.yaml/dispatches \
            -d '{"ref":"main","inputs":{"path":"/service-one","image-name":"service-one"}}'
  destroy-infra:
    needs: end-2-end
    runs-on: ubuntu-latest
    steps:
      - run: echo "⚙️ Destroying testing infrastructure for Application One."
  trigger-dependencies:
    needs: promote
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}"\
            https://api.github.com/repos/devopslord/application-two/actions/workflows/build.yaml/dispatches \
            -d '{"ref":"main","inputs":{"image-name":"service-one"}}'