
on:
  workflow_dispatch:
    inputs:
      path:
        required: true
        type: string
      image-name:
        required: true
        type: string
name: Promote Service One
run-name: ${{ github.actor }} is promoting ${{ inputs.image-name }}
jobs:
  promoting-service-one-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Promoting ${{ inputs.path }} - ${{ inputs.image-name }}"

